(executable
 (name test_chacha20)
 (libraries chacha20 crypto_oracles alcotest qcheck-core qcheck-alcotest)
 (modules harness test_chacha20))

(rule
 (alias runtest)
 (deps
  ../vectors/chacha20/quarter_round.txt
  ../vectors/chacha20/block_function.txt
  ../vectors/chacha20/encryption.txt)
 (action
  (run %{exe:test_chacha20.exe})))
